export const FETCH_RENTALS = "FETCH_RENTALS";
export const FETCH_RENTAL = "FETCH_RENTAL";
export const FETCH_RENTAL_INIT = "FETCH_RENTAL_INIT";
export const FETCH_RENTALS_INIT = "FETCH_RENTALS_INIT";
export const FETCH_RENTALS_FAIL = "FETCH_RENTALS_FAIL";

export const CREATE_RENTAL = "CREATE_RENTAL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
